apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deck-watch
  namespace: {{ .Values.global.namespace }}
  annotations:
    Release.Name: {{ .Release.Name }}
    Release.Revision: "{{ .Release.Revision }}"
    Chart.Name: {{ .Chart.Name }}
    Chart.Version: {{ .Chart.Version }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /deck-watch
        backend:
          serviceName: deck-watch
          servicePort: metrics
