# Sevice
apiVersion: v1
kind: Service
metadata:
  name: deck-watch
  namespace: {{ .Values.global.namespace }}
  labels:
    app: deck-watch
  annotations:
    Release.Name: {{ .Release.Name }}
    Release.Revision: "{{ .Release.Revision }}"
    Chart.Name: {{ .Chart.Name }}
    Chart.Version: {{ .Chart.Version }}
spec:
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deck-watch
  sessionAffinity: None
  type: ClusterIP
