# Sevice
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deck-watch.name" . }}
  namespace: {{ .Values.global.namespace }}
  annotations: {{ include "global.annotations.standard" . | indent 4 }}
  labels:
    app: deck-watch
spec:
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deck-watch
  sessionAffinity: None
  type: ClusterIP
